In [1]:
import pandas as pd
import re
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import pickle

In [2]:
df1 = pd.read_csv(
    "/Users/nilay/Desktop/Dhruv/sentimental Analisis/twitter_training.csv", names=["extra", "source", "sentiment", "content"])
df2 = pd.read_csv("twitter_validation.csv", names=[
                  "extra", "source", "sentiment", "content"])

In [3]:
df = pd.concat([df1, df2], ignore_index=True)

In [4]:
print(df.describe())
print(df.info())

              extra
count  75682.000000
mean    6432.579583
std     3740.243463
min        1.000000
25%     3196.000000
50%     6423.000000
75%     9602.000000
max    13200.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75682 entries, 0 to 75681
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   extra      75682 non-null  int64
 1   source     75682 non-null  object
 2   sentiment  75682 non-null  object
 3   content    74996 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB
None

In [5]:
df

,extra,source,sentiment,content
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
...,...,...,...,...
75677,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
75678,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
75679,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
75680,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
75681,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [6]:
df.drop(columns=['extra', 'source'], axis=1, inplace=True)

In [7]:
ngv = df[df['sentiment'] == 'Negative']

In [8]:
psv = df[df['sentiment'] == 'Positive']

In [9]:
psv['content'].iloc[1121]

'Hmmm or'

In [10]:
ngv['content'].iloc[11]

'<unk> Gearbox really time to fix this 10 drops in the new Borderlands 3 DLC or be fine to force bosses on Mayhem 10 to get a legendary drop while everyone else i get 6-10 drops.. Really needs alot'

In [11]:
df['content'].iloc[11]

'was'

In [12]:
ngv['content'].iloc[1121]

'Researchers disclosed flaws in Amazon Alexa products could allow attackers to access account data and install code on Echo devices...'

In [13]:
df['sentiment'].value_counts()

sentiment
Negative      22808
Positive      21109
Neutral       18603
Irrelevant    13162
Name: count, dtype: int64

In [14]:
df

        sentiment                                            content
0        Positive  im getting on borderlands and i will murder yo...
1        Positive  I am coming to the borders and I will kill you...
2        Positive  im getting on borderlands and i will kill you ...
3        Positive  im coming on borderlands and i will murder you...
4        Positive  im getting on borderlands 2 and i will murder ...
...           ...                                                ...
75677  Irrelevant  ⭐️ Toronto is the arts and culture capital of ...
75678  Irrelevant  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
75679    Positive  Today sucked so it’s time to drink wine n play...
75680    Positive  Bought a fraction of Microsoft today. Small wins.
75681     Neutral  Johnson & Johnson to stop selling talc baby po...

[75682 rows x 2 columns]

In [15]:
df

        sentiment                                            content
0        Positive  im getting on borderlands and i will murder yo...
1        Positive  I am coming to the borders and I will kill you...
2        Positive  im getting on borderlands and i will kill you ...
3        Positive  im coming on borderlands and i will murder you...
4        Positive  im getting on borderlands 2 and i will murder ...
...           ...                                                ...
75677  Irrelevant  ⭐️ Toronto is the arts and culture capital of ...
75678  Irrelevant  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
75679    Positive  Today sucked so it’s time to drink wine n play...
75680    Positive  Bought a fraction of Microsoft today. Small wins.
75681     Neutral  Johnson & Johnson to stop selling talc baby po...

[75682 rows x 2 columns]

In [16]:
df

        sentiment                                            content
0        Positive  im getting on borderlands and i will murder yo...
1        Positive  I am coming to the borders and I will kill you...
2        Positive  im getting on borderlands and i will kill you ...
3        Positive  im coming on borderlands and i will murder you...
4        Positive  im getting on borderlands 2 and i will murder ...
...           ...                                                ...
75677  Irrelevant  ⭐️ Toronto is the arts and culture capital of ...
75678  Irrelevant  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
75679    Positive  Today sucked so it’s time to drink wine n play...
75680    Positive  Bought a fraction of Microsoft today. Small wins.
75681     Neutral  Johnson & Johnson to stop selling talc baby po...

[75682 rows x 2 columns]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75682 entries, 0 to 75681
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sentiment  75682 non-null  object
 1   content    74996 non-null  object
dtypes: object(2)
memory usage: 1.2+ MB

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75682 entries, 0 to 75681
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sentiment  75682 non-null  object
 1   content    74996 non-null  object
dtypes: object(2)
memory usage: 1.2+ MB

In [19]:
df.describe()

       sentiment content
count      75682   74996
unique         4   69974
top     Negative
freq       22808     172

In [20]:
df.describe()

       sentiment content
count      75682   74996
unique         4   69974
top     Negative
freq       22808     172

In [21]:
df.isnull().sum()

sentiment      0
content      686
dtype: int64

In [22]:
df.isnull().sum()

sentiment      0
content      686
dtype: int64

In [23]:
df.isna().sum()

sentiment      0
content      686
dtype: int64

In [24]:
df.dropna(inplace=True)

In [25]:
df.drop_duplicates(subset='content', inplace=True)

In [26]:
df.duplicated(subset='content').sum()

0

In [27]:
df.duplicated(subset='content').sum()

0

In [28]:
df

        sentiment                                            content
0        Positive  im getting on borderlands and i will murder yo...
1        Positive  I am coming to the borders and I will kill you...
2        Positive  im getting on borderlands and i will kill you ...
3        Positive  im coming on borderlands and i will murder you...
4        Positive  im getting on borderlands 2 and i will murder ...
...           ...                                                ...
75670     Neutral  ♥️ Suikoden 2\n1️⃣ Alex Kidd in Miracle World\...
75671    Positive  Thank you to Matching funds Home Depot RW paym...
75673     Neutral  Late night stream with the boys! Come watch so...
75677  Irrelevant  ⭐️ Toronto is the arts and culture capital of ...
75678  Irrelevant  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...

[69974 rows x 2 columns]

In [29]:
df.drop_duplicates(subset='content', inplace=True)

In [30]:
df

        sentiment                                            content
0        Positive  im getting on borderlands and i will murder yo...
1        Positive  I am coming to the borders and I will kill you...
2        Positive  im getting on borderlands and i will kill you ...
3        Positive  im coming on borderlands and i will murder you...
4        Positive  im getting on borderlands 2 and i will murder ...
...           ...                                                ...
75670     Neutral  ♥️ Suikoden 2\n1️⃣ Alex Kidd in Miracle World\...
75671    Positive  Thank you to Matching funds Home Depot RW paym...
75673     Neutral  Late night stream with the boys! Come watch so...
75677  Irrelevant  ⭐️ Toronto is the arts and culture capital of ...
75678  Irrelevant  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...

[69974 rows x 2 columns]

In [31]:
df

        sentiment                                            content
0        Positive  im getting on borderlands and i will murder yo...
1        Positive  I am coming to the borders and I will kill you...
2        Positive  im getting on borderlands and i will kill you ...
3        Positive  im coming on borderlands and i will murder you...
4        Positive  im getting on borderlands 2 and i will murder ...
...           ...                                                ...
75670     Neutral  ♥️ Suikoden 2\n1️⃣ Alex Kidd in Miracle World\...
75671    Positive  Thank you to Matching funds Home Depot RW paym...
75673     Neutral  Late night stream with the boys! Come watch so...
75677  Irrelevant  ⭐️ Toronto is the arts and culture capital of ...
75678  Irrelevant  tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...

[69974 rows x 2 columns]

In [32]:
df['sentiment'].value_counts()

sentiment
Negative      21258
Positive      19200
Neutral       17213
Irrelevant    12303
Name: count, dtype: int64

In [33]:
df['sentiment'].value_counts()

sentiment
Negative      21258
Positive      19200
Neutral       17213
Irrelevant    12303
Name: count, dtype: int64

In [34]:
df['content'].isnull().sum()

0

In [35]:
import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))


def clean_text(text):
    text = text.lower()
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'https?://\S+|www\.\S+|\S+\.\S{2,}', "", text)
    # Remove stopwords
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text


df['content'] = df['content'].apply(clean_text)

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1006)>

In [36]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet


# Download necessary NLTK resources
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

stemmer = PorterStemmer()


def apply_stemming(text):
    words = word_tokenize(text)  # Tokenize words
    stemmed_words = [stemmer.stem(word) for word in words]  # Apply stemming
    return ' '.join(stemmed_words)


# Example usage
df['content'] = df['content'].apply(apply_stemming)

[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1006)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1006)>
[nltk_data] Error loading omw-1.4: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1006)>

In [37]:
df['content'].iloc[84]

'fuck'

In [38]:
df['content'].iloc[6]

'spent hour make someth fun dont know huge fan maya one favorit charact decid make wallpap pc origin imag versu creation made enjoy pictwittercommlsi5wf9jg'

In [39]:
import ssl
import nltk

# Fix SSL issue
try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

# Now, download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /Users/nilay/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [40]:
import nltk
print(nltk.data.path)

['/Users/nilay/nltk_data', '/Library/Frameworks/Python.framework/Versions/3.11/nltk_data', '/Library/Frameworks/Python.framework/Versions/3.11/share/nltk_data', '/Library/Frameworks/Python.framework/Versions/3.11/lib/nltk_data', '/usr/share/nltk_data', '/usr/local/share/nltk_data', '/usr/lib/nltk_data', '/usr/local/lib/nltk_data']

In [41]:

nltk.download('punkt', force=True)

[nltk_data] Downloading package punkt to /Users/nilay/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [42]:
!pip install nltk
import nltk

nltk.download('punkt')
nltk.download('punkt_tab') # download the punkt_tab data package
df['tokens'] = df['content'].apply(word_tokenize)

Requirement already satisfied: nltk in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (3.9.1)
Requirement already satisfied: click in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk) (1.1.1)
Requirement already satisfied: regex>=2021.8.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from nltk) (4.66.1)

[nltk_data] Downloading package punkt to /Users/nilay/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/nilay/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [43]:
df['tokens']

0                            [im, get, borderland, murder]
1                                     [come, border, kill]
2                              [im, get, borderland, kill]
3                           [im, come, borderland, murder]
4                         [im, get, borderland, 2, murder]
                               ...
75670    [suikoden, 2, 1, alex, kidd, miracl, world, pe...
75671    [thank, match, fund, home, depot, rw, payment,...
75673    [late, night, stream, boy, come, watch, warzon...
75677    [toronto, art, cultur, capit, canada, wonder, ...
75678    [actual, good, move, tot, bring, viewer, one, ...
Name: tokens, Length: 69974, dtype: object

In [44]:
df['content'].isnull().sum()

0

In [45]:
le = LabelEncoder()
df['sentiment'] = le.fit_transform(df['sentiment'])

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69974 entries, 0 to 75678
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sentiment  69974 non-null  int64
 1   content    69974 non-null  object
 2   tokens     69974 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.1+ MB

In [47]:
# df.drop(columns=('stemming'), axis=1, inplace=True)

In [48]:
df

,sentiment,content,tokens
0,3,im get borderland murder,"[im, get, borderland, murder]"
1,3,come border kill,"[come, border, kill]"
2,3,im get borderland kill,"[im, get, borderland, kill]"
3,3,im come borderland murder,"[im, come, borderland, murder]"
4,3,im get borderland 2 murder,"[im, get, borderland, 2, murder]"
...,...,...,...
75670,2,suikoden 2 1 alex kidd miracl world persona 3 ...,"[suikoden, 2, 1, alex, kidd, miracl, world, pe..."
75671,3,thank match fund home depot rw payment gener d...,"[thank, match, fund, home, depot, rw, payment,..."
75673,2,late night stream boy come watch warzon run st...,"[late, night, stream, boy, come, watch, warzon..."
75677,0,toronto art cultur capit canada wonder want st...,"[toronto, art, cultur, capit, canada, wonder, ..."
75678,0,actual good move tot bring viewer one peopl go...,"[actual, good, move, tot, bring, viewer, one, ..."

In [49]:
# import pandas as pd
# from textblob import TextBlob

# # # Sample dataset
# # data = {'content': ["I love this product!",
# #                     "This is the worst experience.", "It's okay, not the best."]}
# # df = pd.DataFrame(data)

# # # Function to get sentiment score


# def get_sentiment_score(text):
#     # Returns a score between -1 and 1
#     return TextBlob(text).sentiment.polarity


# # Add sentiment score column
# df['sentiment_score'] = df['content'].apply(get_sentiment_score)

# print(df)

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=50000)  # Keep top 5000 words
X_tfidf = tfidf.fit_transform(df['content'])

print(X_tfidf.shape)  # Check dimensions

(69974, 32672)

In [51]:
df

,sentiment,content,tokens
0,3,im get borderland murder,"[im, get, borderland, murder]"
1,3,come border kill,"[come, border, kill]"
2,3,im get borderland kill,"[im, get, borderland, kill]"
3,3,im come borderland murder,"[im, come, borderland, murder]"
4,3,im get borderland 2 murder,"[im, get, borderland, 2, murder]"
...,...,...,...
75670,2,suikoden 2 1 alex kidd miracl world persona 3 ...,"[suikoden, 2, 1, alex, kidd, miracl, world, pe..."
75671,3,thank match fund home depot rw payment gener d...,"[thank, match, fund, home, depot, rw, payment,..."
75673,2,late night stream boy come watch warzon run st...,"[late, night, stream, boy, come, watch, warzon..."
75677,0,toronto art cultur capit canada wonder want st...,"[toronto, art, cultur, capit, canada, wonder, ..."
75678,0,actual good move tot bring viewer one peopl go...,"[actual, good, move, tot, bring, viewer, one, ..."

In [52]:
x = X_tfidf
y = df['sentiment']

In [53]:
x[0]

<1x32672 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [54]:
y[0]

3

In [55]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=.2, random_state=42)

In [56]:
print(x_test.shape, y_test.shape)

(13995, 32672) (13995,)

In [57]:
y_test.shape

(13995,)

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize Logistic Regression model
model = LogisticRegression()

# Train the model
model.fit(x_train, y_train)

# Predict on the test set
y_pred = model.predict(x_test)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [59]:
# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

# Display Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Display Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

Model Accuracy: 0.7370
Confusion Matrix:
[[1467  330  246  365]
 [ 152 3540  309  341]
 [ 210  419 2360  436]
 [ 189  353  330 2948]]
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.61      0.66      2408
           1       0.76      0.82      0.79      4342
           2       0.73      0.69      0.71      3425
           3       0.72      0.77      0.75      3820

    accuracy                           0.74     13995
   macro avg       0.73      0.72      0.73     13995
weighted avg       0.74      0.74      0.74     13995

In [60]:
with open("model.pkl", "wb") as f:
    pickle.dump((tfidf, model), f)

In [61]:
y[4]

3

In [62]:
model.predict(x[4])

array([3])

Positive Tweets 😊

Absolutely thrilled with my new smartwatch! The features are incredible, and it’s super lightweight. A great buy!
Had an amazing dinner at this restaurant! The food was delicious, and the service was top-notch. Highly recommended! 
Just watched the latest movie, and wow! The story, the acting, everything was perfect. Best film of the year!
My package arrived earlier than expected! Super happy with the fast delivery and great product quality.
Such a productive day at work today! Feeling accomplished and motivated for what’s next.[0]

Negative Tweets 😡

This is the worst customer service I’ve ever experienced. Kept me on hold for an hour and then disconnected!
The software update is a disaster. My phone keeps crashing, and nothing seems to work properly anymore!
Bought these headphones last week, and they stopped working already. Total waste of money.
The flight got delayed by 4 hours, and there was no communication from the airline. So frustrating!     
Terrible experience at this café. The coffee was cold, and the staff was rude. Never going back!    

Neutral Tweets 😐

Just finished reading a book about space exploration. It had some interesting facts.
I need to get a new laptop soon. Not sure which one to go for yet.[1]
The new policy changes at work were announced today. Need to read through them later.
Checking out the new menu at this restaurant. It has some interesting options. 
It’s been a long day. Just relaxing now and catching up on some news.

In [63]:
# cleaning
documents = input("Enter the tweet for texting")
doc = clean_text(documents)
print("text_clean = ", doc)
# stemming
doc = apply_stemming(doc)
# vectorization
v = tfidf.transform([doc])
print("text_shape", v.shape)
model.predict(v)

text_clean =  cozz hey long time see yes rains bit bit lol im fine thanks hows
text_shape (1, 32672)

array([3])

In [64]:
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


model1 = svm.SVC(kernel='linear')

# Train the model
model1.fit(x_train, y_train)

# Predict on the test set
y_pred = model1.predict(x_test)

In [65]:
# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

# Display Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Display Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

Model Accuracy: 0.7907
Confusion Matrix:
[[1688  255  167  298]
 [ 112 3740  207  283]
 [ 189  371 2525  340]
 [ 172  297  238 3113]]
Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.70      0.74      2408
           1       0.80      0.86      0.83      4342
           2       0.80      0.74      0.77      3425
           3       0.77      0.81      0.79      3820

    accuracy                           0.79     13995
   macro avg       0.79      0.78      0.78     13995
weighted avg       0.79      0.79      0.79     13995

Positive Tweets 😊

Absolutely thrilled with my new smartwatch! The features are incredible, and it’s super lightweight. A great buy!
Had an amazing dinner at this restaurant! The food was delicious, and the service was top-notch. Highly recommended!  
Just watched the latest movie, and wow! The story, the acting, everything was perfect. Best film of the year! 
My package arrived earlier than expected! Super happy with the fast delivery and great product quality.
Such a productive day at work today! Feeling accomplished and motivated for what’s next.[0]

Negative Tweets 😡

This is the worst customer service I’ve ever experienced. Kept me on hold for an hour and then disconnected!
The software update is a disaster. My phone keeps crashing, and nothing seems to work properly anymore!
Bought these headphones last week, and they stopped working already. Total waste of money.
The flight got delayed by 4 hours, and there was no communication from the airline. So frustrating!     
Terrible experience at this café. The coffee was cold, and the staff was rude. Never going back!    [3]

Neutral Tweets 😐

Just finished reading a book about space exploration. It had some interesting facts.
I need to get a new laptop soon. Not sure which one to go for yet.[1]
The new policy changes at work were announced today. Need to read through them later.
Checking out the new menu at this restaurant. It has some interesting options.  
It’s been a long day. Just relaxing now and catching up on some news.

In [66]:
# SVM
# cleaning
documents = input("Enter the tweet for texting")
doc = clean_text(documents)
print("text_clean = ", doc)

# stemming
doc = apply_stemming(doc)

# vectorization
v = tfidf.transform([doc])
print("text_shape", v.shape)
model1.predict(v)

text_clean =  pardonlaureni repierced ears
text_shape (1, 32672)

array([2])

In [67]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


model2 = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
model2.fit(x_train, y_train)

# Predict on the test set
y_pred = model2.predict(x_test)

In [68]:
# Calculate Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

# Display Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Display Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

Model Accuracy: 0.9175
Confusion Matrix:
[[2039  155   61  153]
 [  29 4145   67  101]
 [  20  169 3098  138]
 [  32  153   76 3559]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.85      0.90      2408
           1       0.90      0.95      0.92      4342
           2       0.94      0.90      0.92      3425
           3       0.90      0.93      0.92      3820

    accuracy                           0.92     13995
   macro avg       0.92      0.91      0.92     13995
weighted avg       0.92      0.92      0.92     13995

Positive Tweets 😊

Absolutely thrilled with my new smartwatch! The features are incredible, and it’s super lightweight. A great buy!
Had an amazing dinner at this restaurant! The food was delicious, and the service was top-notch. Highly recommended!  
Just watched the latest movie, and wow! The story, the acting, everything was perfect. Best film of the year!
My package arrived earlier than expected! Super happy with the fast delivery and great product quality.
Such a productive day at work today! Feeling accomplished and motivated for what’s next.[2]

Negative Tweets 😡

This is the worst customer service I’ve ever experienced. Kept me on hold for an hour and then disconnected!
The software update is a disaster. My phone keeps crashing, and nothing seems to work properly anymore!
Bought these headphones last week, and they stopped working already. Total waste of money.
The flight got delayed by 4 hours, and there was no communication from the airline. So frustrating!     
Terrible experience at this café. The coffee was cold, and the staff was rude. Never going back!    

Neutral Tweets 😐

Just finished reading a book about space exploration. It had some interesting facts.
I need to get a new laptop soon. Not sure which one to go for yet.[0]
The new policy changes at work were announced today. Need to read through them later.[3]
Checking out the new menu at this restaurant. It has some interesting options. 
It’s been a long day. Just relaxing now and catching up on some news.[3]

In [69]:
# Random Forest Classifier
# cleaning
documents = input("Enter the tweet for texting")
doc = clean_text(documents)
print("text_clean = ", doc)

# stemming
doc = apply_stemming(doc)

# vectorization
v = tfidf.transform([doc])
print("text_shape", v.shape)
model2.predict(v)

text_clean =  pardonlaureni repierced ears
text_shape (1, 32672)

array([1])

In [70]:
df

,sentiment,content,tokens
0,3,im get borderland murder,"[im, get, borderland, murder]"
1,3,come border kill,"[come, border, kill]"
2,3,im get borderland kill,"[im, get, borderland, kill]"
3,3,im come borderland murder,"[im, come, borderland, murder]"
4,3,im get borderland 2 murder,"[im, get, borderland, 2, murder]"
...,...,...,...
75670,2,suikoden 2 1 alex kidd miracl world persona 3 ...,"[suikoden, 2, 1, alex, kidd, miracl, world, pe..."
75671,3,thank match fund home depot rw payment gener d...,"[thank, match, fund, home, depot, rw, payment,..."
75673,2,late night stream boy come watch warzon run st...,"[late, night, stream, boy, come, watch, warzon..."
75677,0,toronto art cultur capit canada wonder want st...,"[toronto, art, cultur, capit, canada, wonder, ..."
75678,0,actual good move tot bring viewer one peopl go...,"[actual, good, move, tot, bring, viewer, one, ..."

In [71]:
df['sentiment'].value_counts()

sentiment
1    21258
3    19200
2    17213
0    12303
Name: count, dtype: int64

In [72]:
df

,sentiment,content,tokens
0,3,im get borderland murder,"[im, get, borderland, murder]"
1,3,come border kill,"[come, border, kill]"
2,3,im get borderland kill,"[im, get, borderland, kill]"
3,3,im come borderland murder,"[im, come, borderland, murder]"
4,3,im get borderland 2 murder,"[im, get, borderland, 2, murder]"
...,...,...,...
75670,2,suikoden 2 1 alex kidd miracl world persona 3 ...,"[suikoden, 2, 1, alex, kidd, miracl, world, pe..."
75671,3,thank match fund home depot rw payment gener d...,"[thank, match, fund, home, depot, rw, payment,..."
75673,2,late night stream boy come watch warzon run st...,"[late, night, stream, boy, come, watch, warzon..."
75677,0,toronto art cultur capit canada wonder want st...,"[toronto, art, cultur, capit, canada, wonder, ..."
75678,0,actual good move tot bring viewer one peopl go...,"[actual, good, move, tot, bring, viewer, one, ..."

In [73]:
# import pandas as pd
# from textblob import TextBlob

# # # Sample dataset
# # data = {'content': ["I love this product!",
# #                     "This is the worst experience.", "It's okay, not the best."]}
# # df = pd.DataFrame(data)

# # # Function to get sentiment score


# def get_sentiment_score(text):
#     # Returns a score between -1 and 1
#     return TextBlob(text).sentiment.polarity


# # Add sentiment score column
# df['sentiment_score'] = df['content'].apply(get_sentiment_score)

# print(df)

SEO score